Added project for Daniel^2
matematiflo/Comp_assisted_math pull request #28
Opened 2023-07-24 07:38 UTC by fadoeng

2023-07-24 14:57 UTC, matematiflo commented on Lean/Students_projects/Daniel^2/Daniel^2_FTA_Corollary4.pdf
This needs to be reviewed. As stated, the statement does not quite make sense. Is the conclusion the fact that the two commuting operators have a common eigenvector? If so, it is not stated in this way. Please review and fix this, thanks!

2023-07-24 14:58 UTC, matematiflo requested changes
Please see the separate review of the pdf file

2023-07-25 13:27 UTC, fadoeng commented
Added the statement in the .pdf file

2023-07-25 13:29 UTC, fadoeng commented
Is this possible to merge? I'm kinda confused with GitHub now.

2023-07-25 14:16 UTC, merged